import { KeyAction } from "@/lib/enums/keyAction";
import type { ButtonZone, Skin } from "@/lib/interfaces/skin";

/**
 * Zones for the 948x2160 photo in public/img/nokia-3310.webp.
 *
 * Percentages are of the phone image box. To fit another photo, open /studio,
 * drag the zones onto its keys, and paste the results into this file.
 */
export const ZONES: ButtonZone[] = [
  {
    key: KeyAction.Clear,
    label: "C",
    debugColor: "#9b59b655",
    top: "55%",
    left: "18%",
    width: "15%",
    height: "6%",
  },
  {
    key: KeyAction.Center,
    label: "OK",
    debugColor: "#2980b955",
    top: "52%",
    left: "34%",
    width: "33%",
    height: "4%",
  },
  {
    key: KeyAction.NavLeft,
    label: "left",
    debugColor: "#e74c3c55",
    top: "58%",
    left: "57%",
    width: "13%",
    height: "6%",
  },
  {
    key: KeyAction.NavRight,
    label: "right",
    debugColor: "#e67e2255",
    top: "54%",
    left: "71%",
    width: "13%",
    height: "6%",
  },
  {
    key: KeyAction.Key1,
    label: "1",
    debugColor: "#f39c1255",
    top: "65%",
    left: "12%",
    width: "20%",
    height: "5%",
    rotate: 20,
  },
  {
    key: KeyAction.Key2,
    label: "2 abc",
    debugColor: "#f1c40f55",
    top: "66.5%",
    left: "39.5%",
    width: "22%",
    height: "5%",
  },
  {
    key: KeyAction.Key3,
    label: "3 def",
    debugColor: "#e74c3c55",
    top: "65%",
    left: "68%",
    width: "21%",
    height: "5%",
    rotate: -20,
  },
  {
    key: KeyAction.Key4,
    label: "4 ghi",
    debugColor: "#e67e2255",
    top: "72%",
    left: "13%",
    width: "21%",
    height: "5.3%",
    rotate: 21,
  },
  {
    key: KeyAction.Key5,
    label: "5 jkl",
    debugColor: "#2ecc7155",
    top: "73.5%",
    left: "39.3%",
    width: "22%",
    height: "5.4%",
  },
  {
    key: KeyAction.Key6,
    label: "6 mno",
    debugColor: "#1abc9c55",
    top: "72%",
    left: "67%",
    width: "21%",
    height: "5.3%",
    rotate: -21,
  },
  {
    key: KeyAction.Key7,
    label: "7 pqrs",
    debugColor: "#3498db55",
    top: "79.1%",
    left: "14%",
    width: "20.4%",
    height: "5.3%",
    rotate: 20,
  },
  {
    key: KeyAction.Key8,
    label: "8 tuv",
    debugColor: "#9b59b655",
    top: "80.5%",
    left: "39%",
    width: "22%",
    height: "5.3%",
  },
  {
    key: KeyAction.Key9,
    label: "9 wxyz",
    debugColor: "#e91e6355",
    top: "79.1%",
    left: "66%",
    width: "21%",
    height: "5.3%",
    rotate: -21,
  },
  {
    key: KeyAction.Star,
    label: "star",
    debugColor: "#95a5a655",
    top: "86.1%",
    left: "14%",
    width: "22%",
    height: "5.4%",
    rotate: 21,
  },
  {
    key: KeyAction.Key0,
    label: "0",
    debugColor: "#bdc3c755",
    top: "87.5%",
    left: "39.2%",
    width: "22%",
    height: "5.7%",
  },
  {
    key: KeyAction.Hash,
    label: "hash",
    debugColor: "#7f8c8d55",
    top: "86.1%",
    left: "64.6%",
    width: "22%",
    height: "5.4%",
    rotate: -21,
  },
];

export const nokia3310: Skin = {
  name: "Nokia 3310",
  image: "/img/nokia-3310.webp",
  aspectRatio: 948 / 2160,
  screen: { top: "26.2%", left: "16.4%", width: "67.7%", height: "21.5%" },
  screenClip: "polygon(0% 0%, 100% 0%, 97% 100%, 3% 100%)",
  palette: {
    bg: "#9bbc0f",
    dark: "#0f380f",
    mid: "#306230",
    light: "#8bac0f",
  },
  scanlines: true,
  zones: ZONES,
};
